"use client";
import {BrandMark} from "@/components/brand-mark";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {Eye,EyeOff} from "lucide-react";
import {Capacitor} from "@capacitor/core";
import {api,OAUTH_ORIGIN,OAUTH_READY} from "@/lib/api";
export default function Login(){
 const demo=process.env.NEXT_PUBLIC_SHOW_DEMO==="true",router=useRouter();const[register,setRegister]=useState(false),[email,setEmail]=useState(demo?"minji@toogeduler.app":""),[password,setPassword]=useState(demo?"password123!":""),[name,setName]=useState(""),[error,setError]=useState(""),[show,setShow]=useState(false),[loading,setLoading]=useState(false);
 const[notice,setNotice]=useState("");
 useEffect(()=>{const params=new URLSearchParams(location.search);if(params.get("deleted")==="1"){setNotice("계정이 삭제되었습니다. 그동안 이용해 주셔서 감사합니다.");return}const code=params.get("oauthError");if(code==="email")setError("소셜 계정에서 이메일 제공에 동의해주세요.");else if(code)setError(`소셜 인증 오류 (${code})가 발생했습니다. 잠시 후 다시 시도해주세요.`)},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const result=await api<{token:string}>(`/api/auth/${register?"register":"login"}`,{method:"POST",body:JSON.stringify(register?{email,password,name}:{email,password})});localStorage.setItem("toogeduler_token",result.token);const invite=sessionStorage.getItem("pending_invite");if(invite){sessionStorage.removeItem("pending_invite");router.push(`/invite/${invite}`)}else router.push("/");}catch(e){setError(e instanceof Error?e.message:"로그인에 실패했습니다.");}finally{setLoading(false)}}
 const oauthUrl=(provider:"kakao"|"google")=>`${OAUTH_ORIGIN}${Capacitor.isNativePlatform()?`/api/auth/mobile-oauth/${provider}`:`/oauth2/authorization/${provider}`}`;
 return <main className="login-page"><section className="login-story"><div className="brand brand-light"><BrandMark/>Toogeduler</div><div className="story-copy"><h1>우리가 만날<br/>시간을 한눈에.</h1><p>각자의 일정은 필요한 만큼만 나누고,<br/>모두가 되는 순간은 빠르게 찾으세요.</p></div><div className="overlap-hero" aria-hidden="true"><div className="lane lane-a"><b>민지</b><span>토요일 오후 1시–5시</span></div><div className="lane lane-b"><b>서준</b><span>토요일 오후 3시–8시</span></div><div className="meet"><b>오후 3시</b><span>둘 다 비어 있어요</span></div></div></section><section className="login-panel"><form onSubmit={submit}><div className="mobile-brand"><BrandMark/>Toogeduler</div><p className="panel-kicker">반가워요</p><h2>{register?"새 계정 만들기":"내 캘린더로 돌아가기"}</h2><p className="muted">{register?"몇 초면 준비가 끝나요.":"일정과 사람들을 이어서 확인하세요."}</p>{register&&<label>이름<input value={name} onChange={e=>setName(e.target.value)} placeholder="어떻게 불러드릴까요?" required minLength={2}/></label>}<label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<span className="password-wrap"><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/><button type="button" onClick={()=>setShow(!show)} aria-label="비밀번호 보기">{show?<EyeOff/>:<Eye/>}</button></span></label>{notice&&<p className="form-notice">{notice}</p>}{error&&<p className="form-error">{error}</p>}<button className="primary full" disabled={loading}>{loading?"확인 중...":register?"계정 만들기":"로그인"}</button>{OAUTH_READY&&<><div className="or"><span>또는</span></div><div className="social-row"><a href={oauthUrl("kakao")} className="social kakao" aria-label="Kakao로 로그인"><b>K</b><span>Kakao로 계속</span></a><a href={oauthUrl("google")} className="social google" aria-label="Google로 로그인"><b>G</b><span>Google로 계속</span></a></div></>}<button type="button" className="switch-auth" onClick={()=>setRegister(!register)}>{register?"이미 계정이 있나요? 로그인":"처음인가요? 계정 만들기"}</button>{demo&&<p className="demo-hint">데모: minji@toogeduler.app / password123!</p>}<p className="legal-links"><a href="/terms">이용약관</a><span aria-hidden="true">·</span><a href="/privacy">개인정보처리방침</a></p></form></section></main>
}
