"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowRight,CalendarDays,Eye,EyeOff,UsersRound} from "lucide-react";
import {api,API} from "@/lib/api";
export default function Login(){
 const router=useRouter();const[register,setRegister]=useState(false);const[email,setEmail]=useState("minji@toogeduler.app");const[password,setPassword]=useState("password123!");const[name,setName]=useState("");const[error,setError]=useState("");const[show,setShow]=useState(false);const[loading,setLoading]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const result=await api<{token:string}>(`/api/auth/${register?"register":"login"}`,{method:"POST",body:JSON.stringify(register?{email,password,name}:{email,password})});localStorage.setItem("toogeduler_token",result.token);const invite=sessionStorage.getItem("pending_invite");if(invite){sessionStorage.removeItem("pending_invite");router.push(`/invite/${invite}`)}else router.push("/");}catch(e){setError(e instanceof Error?e.message:"로그인에 실패했습니다.");}finally{setLoading(false)}}
 return <main className="login-page"><section className="login-story"><div className="brand brand-light"><span className="brand-mark"><CalendarDays size={19}/></span>Toogeduler</div><div className="story-copy"><p className="eyebrow">TOGETHER, ON TIME</p><h1>우리가 만날<br/>시간을 한눈에.</h1><p>각자의 일정은 필요한 만큼만 나누고,<br/>모두가 되는 순간은 빠르게 찾으세요.</p></div><div className="time-ripples" aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="story-note"><UsersRound size={18}/><span><b>3명이 함께 가능한 시간</b><small>토요일 오후 3:00 · 2시간</small></span></div></section><section className="login-panel"><form onSubmit={submit}><div className="mobile-brand"><span className="brand-mark"><CalendarDays size={18}/></span>Toogeduler</div><p className="panel-kicker">반가워요</p><h2>{register?"새 계정 만들기":"내 캘린더로 돌아가기"}</h2><p className="muted">{register?"몇 초면 준비가 끝나요.":"일정과 사람들을 이어서 확인하세요."}</p>{register&&<label>이름<input value={name} onChange={e=>setName(e.target.value)} placeholder="어떻게 불러드릴까요?" required minLength={2}/></label>}<label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<span className="password-wrap"><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/><button type="button" onClick={()=>setShow(!show)} aria-label="비밀번호 보기">{show?<EyeOff/>:<Eye/>}</button></span></label>{error&&<p className="form-error">{error}</p>}<button className="primary full" disabled={loading}>{loading?"확인 중...":register?"시작하기":"로그인"}<ArrowRight size={18}/></button><div className="or"><span>또는</span></div><div className="social-row"><a href={`${API}/oauth2/authorization/kakao`} className="social kakao">K</a><a href={`${API}/oauth2/authorization/google`} className="social google">G</a></div><button type="button" className="switch-auth" onClick={()=>setRegister(!register)}>{register?"이미 계정이 있나요? 로그인":"처음인가요? 계정 만들기"}</button><p className="demo-hint">데모: minji@toogeduler.app / password123!</p></form></section></main>
}
