"use client";

import {useEffect,useMemo,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {addDays,addMonths,addWeeks,differenceInMinutes,format,isSameDay,isSameMonth,isToday,parseISO,startOfMonth,startOfWeek,subMonths,subWeeks} from "date-fns";
import {ko} from "date-fns/locale";
import {ArrowLeft,CalendarDays,ChevronLeft,ChevronRight,Clock3,MapPin,ShieldCheck,UserRound,X} from "lucide-react";
import {api,token} from "@/lib/api";
import type {CalendarEvent,User} from "@/lib/types";

type FriendProfile=User&{friendSince:string};
type ViewMode="week"|"month";
const HOURS=Array.from({length:18},(_,index)=>index+6);

export default function FriendCalendarPage(){
 const params=useParams<{id:string}>();const router=useRouter();const friendId=Number(params.id);
 const[friend,setFriend]=useState<FriendProfile|null>(null);const[events,setEvents]=useState<CalendarEvent[]>([]);const[view,setView]=useState<ViewMode>("month");const[anchor,setAnchor]=useState(new Date());const[selected,setSelected]=useState<CalendarEvent|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const range=useMemo(()=>{const start=view==="week"?startOfWeek(anchor,{weekStartsOn:1}):startOfWeek(startOfMonth(anchor),{weekStartsOn:1});return{start,end:addDays(start,view==="week"?7:42)}},[anchor,view]);
 useEffect(()=>{if(!token()){router.replace("/login");return}api<FriendProfile>(`/api/friends/${friendId}`).then(setFriend).catch(e=>setError(e instanceof Error?e.message:"친구 프로필을 불러오지 못했습니다."))},[friendId,router]);
 useEffect(()=>{if(!token())return;setLoading(true);setError("");api<CalendarEvent[]>(`/api/friends/${friendId}/events?from=${range.start.toISOString()}&to=${range.end.toISOString()}`).then(setEvents).catch(e=>setError(e instanceof Error?e.message:"친구의 일정을 불러오지 못했습니다.")).finally(()=>setLoading(false))},[friendId,range.start.getTime(),range.end.getTime()]);
 const move=(direction:-1|1)=>setAnchor(current=>view==="week"?(direction<0?subWeeks(current,1):addWeeks(current,1)):(direction<0?subMonths(current,1):addMonths(current,1)));
 if(error&&!friend)return <main className="focused-page friend-calendar-page"><PageHeader back={()=>router.push("/?tab=friends")}/><section className="friend-calendar-error"><ShieldCheck/><h1>친구 캘린더를 열 수 없어요</h1><p>{error}</p><button className="primary" onClick={()=>router.push("/?tab=friends")}>친구 목록으로</button></section></main>;
 return <main className="focused-page friend-calendar-page"><PageHeader back={()=>router.push("/?tab=friends")}/><section className="friend-calendar-wrap">{friend?<header className="friend-profile-hero"><div className="friend-profile-avatar">{friend.avatarUrl?<img src={friend.avatarUrl} alt=""/>:<span>{friend.name.slice(-2)}</span>}<i><UserRound/></i></div><div className="friend-profile-copy"><p className="eyebrow">SHARED WITH YOU</p><h1>{friend.name}의 캘린더</h1><p>친구 공개 또는 전체 공개로 나눈 일정만 보여요.</p></div><div className="shared-ribbon"><span><i/><b>친구 연결됨</b></span><small>{friend.friendSince?`${format(parseISO(friend.friendSince),"yyyy년 M월 d일")}부터`:"일정을 공유하고 있어요"}</small></div></header>:<div className="friend-hero-loading"><span className="loader"/></div>}<div className="friend-calendar-toolbar"><div className="period"><button className="today" onClick={()=>setAnchor(new Date())}>오늘</button><button className="nav-arrow" aria-label="이전" onClick={()=>move(-1)}><ChevronLeft/></button><button className="nav-arrow" aria-label="다음" onClick={()=>move(1)}><ChevronRight/></button><h2>{view==="week"?`${format(range.start,"M월 d일")} – ${format(addDays(range.end,-1),"M월 d일")}`:format(anchor,"yyyy년 M월")}</h2></div><div className="segmented" aria-label="캘린더 보기"><button className={view==="week"?"active":""} onClick={()=>setView("week")}>주</button><button className={view==="month"?"active":""} onClick={()=>setView("month")}>월</button></div></div><section className="friend-calendar-surface">{loading?<div className="friend-calendar-loading"><span className="loader"/>공유 일정을 불러오고 있어요</div>:view==="week"?<FriendWeek anchor={anchor} events={events} open={setSelected}/>:<FriendMonth anchor={anchor} events={events} open={setSelected}/>}</section><footer className="friend-calendar-note"><ShieldCheck/><span>비공개 일정과 다른 그룹에만 공개된 일정은 표시되지 않습니다.</span><b>{events.length}개 일정</b></footer></section>{selected&&<EventDetail event={selected} close={()=>setSelected(null)}/>}</main>;
}

function PageHeader({back}:{back:()=>void}){return <header className="focused-header"><button className="back-link" onClick={back}><ArrowLeft/>친구 목록</button><div className="brand"><span className="brand-mark"><CalendarDays/></span>Toogeduler</div><span/></header>}

function FriendWeek({anchor,events,open}:{anchor:Date;events:CalendarEvent[];open:(event:CalendarEvent)=>void}){const days=Array.from({length:7},(_,index)=>addDays(startOfWeek(anchor,{weekStartsOn:1}),index));return <div className="week-calendar friend-week"><div className="week-head"><div className="tz">GMT+9</div>{days.map(day=><div key={day.toISOString()} className={isToday(day)?"today-col":""}><span>{format(day,"EEE",{locale:ko})}</span><b>{format(day,"d")}</b></div>)}</div><div className="all-day-row"><div>종일</div>{days.map(day=><div key={day.toISOString()}>{events.filter(event=>event.allDay&&isSameDay(parseISO(event.startAt),day)).map(event=><button key={`${event.id}-${event.startAt}`} className="all-day-event" style={{background:event.color}} onClick={()=>open(event)}>{event.title}</button>)}</div>)}</div><div className="week-scroll"><div className="time-axis">{HOURS.map((hour,index)=><span key={hour} style={{top:`${index/(HOURS.length-1)*100}%`}}>{hour<12?`오전 ${hour}`:hour===12?"오후 12":`오후 ${hour-12}`}</span>)}</div>{days.map(day=><div key={day.toISOString()} className={`day-lane ${isToday(day)?"is-today":""}`}>{HOURS.map((hour,index)=><i className="hour-line" style={{top:`${index/(HOURS.length-1)*100}%`}} key={hour}/>)}{events.filter(event=>!event.allDay&&isSameDay(parseISO(event.startAt),day)).map(event=>{const start=parseISO(event.startAt),end=parseISO(event.endAt);const startMinute=(start.getHours()-6)*60+start.getMinutes();const length=Math.max(30,differenceInMinutes(end,start));if(startMinute+length<0||startMinute>18*60)return null;return <button key={`${event.id}-${event.startAt}`} className="event-block" style={{top:`${Math.max(0,startMinute)/(18*60)*100}%`,height:`${Math.min(length,18*60-Math.max(0,startMinute))/(18*60)*100}%`,background:`color-mix(in srgb, ${event.color} 14%, white)`,borderColor:event.color}} onClick={()=>open(event)}><span style={{color:event.color}}>{event.title}</span><small>{format(start,"HH:mm")}</small></button>})}</div>)}</div></div>}

function FriendMonth({anchor,events,open}:{anchor:Date;events:CalendarEvent[];open:(event:CalendarEvent)=>void}){const first=startOfWeek(startOfMonth(anchor),{weekStartsOn:1});const days=Array.from({length:42},(_,index)=>addDays(first,index));return <div className="month-calendar friend-month"><div className="month-head">{["월","화","수","목","금","토","일"].map(day=><span key={day}>{day}</span>)}</div><div className="month-grid">{days.map(day=>{const dayEvents=events.filter(event=>isSameDay(parseISO(event.startAt),day));return <div key={day.toISOString()} className={`${!isSameMonth(day,anchor)?"outside":""} ${isToday(day)?"today-cell":""}`}><b>{format(day,"d")}</b>{dayEvents.slice(0,3).map(event=><button key={`${event.id}-${event.startAt}`} onClick={()=>open(event)}><i style={{background:event.color}}/>{event.title}<small>{event.allDay?"종일":format(parseISO(event.startAt),"HH:mm")}</small></button>)}{dayEvents.length>3&&<span className="more-events">+{dayEvents.length-3}개 더</span>}</div>})}</div></div>}

function EventDetail({event,close}:{event:CalendarEvent;close:()=>void}){return <div className="modal-scrim" onMouseDown={e=>e.target===e.currentTarget&&close()}><article className="friend-event-detail"><header><span style={{background:event.color}}/><div><small>{event.visibilities.includes("PUBLIC")?"전체 공개 일정":"친구 공개 일정"}</small><h2>{event.title}</h2></div><button className="icon-btn" onClick={close} aria-label="닫기"><X/></button></header><div className="friend-event-meta"><Clock3/><span><b>{format(parseISO(event.startAt),"M월 d일 EEEE",{locale:ko})}</b><small>{event.allDay?"종일":`${format(parseISO(event.startAt),"HH:mm")} – ${format(parseISO(event.endAt),"HH:mm")}`}</small></span></div>{event.location&&<div className="friend-event-meta"><MapPin/><span><b>{event.location}</b></span></div>}{event.description&&<p>{event.description}</p>}<footer><button className="primary" onClick={close}>확인</button></footer></article></div>}
