"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowLeft,CalendarDays,Camera,Check,Copy,LogOut,Mail,ShieldCheck,UserRound,UsersRound} from "lucide-react";
import {api,token} from "@/lib/api";
import type {User,UserStats} from "@/lib/types";

export default function MyPage(){
 const router=useRouter();const[user,setUser]=useState<User|null>(null);const[stats,setStats]=useState<UserStats|null>(null);const[name,setName]=useState("");const[avatarUrl,setAvatarUrl]=useState("");const[error,setError]=useState("");const[saved,setSaved]=useState(false);const[loading,setLoading]=useState(false);
 useEffect(()=>{if(!token()){router.replace("/login");return}api<User>("/api/auth/me").then(u=>{setUser(u);setName(u.name);setAvatarUrl(u.avatarUrl||"");api<UserStats>("/api/auth/me/stats").then(setStats).catch(()=>setStats({eventCount:0,groupCount:0,friendCount:0}))}).catch(()=>{localStorage.removeItem("toogeduler_token");router.replace("/login")})},[router]);
 async function save(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const updated=await api<User>("/api/auth/me",{method:"PATCH",body:JSON.stringify({name,avatarUrl})});setUser(updated);setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(e){setError(e instanceof Error?e.message:"프로필을 저장하지 못했습니다.")}finally{setLoading(false)}}
 function logout(){localStorage.removeItem("toogeduler_token");router.push("/login")}
 if(!user)return <main className="center-state"><span className="loader"/>내 정보를 불러오고 있어요</main>;
 return <main className="focused-page profile-page"><header className="focused-header"><button className="back-link" onClick={()=>router.push("/")}><ArrowLeft/>캘린더</button><div className="brand"><span className="brand-mark"><CalendarDays/></span>Toogeduler</div><button className="feed-login logout-link" onClick={logout}><LogOut/>로그아웃</button></header><section className="profile-wrap"><header className="profile-identity"><div className="profile-avatar">{avatarUrl?<img src={avatarUrl} alt="프로필"/>:<span>{user.name.slice(-2)}</span>}<i><Camera/></i></div><div><p className="eyebrow">MY TOOGEDULER</p><h1>{user.name}</h1><span>{user.email}</span></div></header><div className="friend-code-card"><span><small>내 친구 코드</small><b>{user.friendCode}</b></span><button onClick={()=>{navigator.clipboard.writeText(user.friendCode);setSaved(true);setTimeout(()=>setSaved(false),1800)}}><Copy/>코드 복사</button><p>카카오 가입자는 이 코드를 친구에게 알려주세요.</p></div><div className="profile-stats"><article><CalendarDays/><span><b>{stats?.eventCount??0}</b><small>내 일정</small></span></article><article><UsersRound/><span><b>{stats?.groupCount??0}</b><small>참여 그룹</small></span></article><article><UserRound/><span><b>{stats?.friendCount??0}</b><small>친구</small></span></article></div><div className="profile-grid"><form className="profile-card" onSubmit={save}><header><div><h2>프로필</h2><p>다른 사람에게 표시되는 정보를 관리합니다.</p></div>{saved&&<span className="saved"><Check/>복사 또는 저장 완료</span>}</header><label>이름<input required minLength={2} maxLength={30} value={name} onChange={e=>setName(e.target.value)}/></label><label>프로필 이미지 주소<input type="url" value={avatarUrl} onChange={e=>setAvatarUrl(e.target.value)} placeholder="https://..."/><small>비워두면 이름으로 만든 기본 이미지가 표시됩니다.</small></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={loading}>{loading?"저장 중...":"변경 사항 저장"}</button></form><aside className="account-card"><h2>계정 정보</h2><div><Mail/><span><small>로그인 계정</small><b>{user.email}</b></span></div><div><ShieldCheck/><span><small>로그인 방식</small><b>{user.provider==="LOCAL"?"이메일 계정":"소셜 계정"}</b></span></div><p>가입일 {user.createdAt?new Intl.DateTimeFormat("ko-KR",{dateStyle:"long"}).format(new Date(user.createdAt)):"-"}</p></aside></div></section></main>
}
